name: Check MurmurHash collisions

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  murmur:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r .scripts/hash_collision_checker/requirements.txt

    - name: Run murmur collision check
      run: |
        python .scripts/hash_collision_checker/check_murmur.py localization/english localization/replace --vanilla .scripts/hash_collision_checker/vanilla_keys.txt
