name: Find braces mismatches
on: [push]
jobs:
  find_braces_mismatches:
    runs-on: ubuntu-latest
    steps:
      - run: |
          wget https://raw.githubusercontent.com/IhateTrains/braces-mismatch-finder/main/bracket_script.py
          echo "Script downloaded"
          python3 bracket_script.py
